# Generated by Django 5.0.4 on 2024-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
