# Generated by Django 5.0.5 on 2024-05-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmManagerFundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_type', models.CharField(max_length=100)),
                ('years_established', models.IntegerField()),
                ('currency_managed', models.CharField(max_length=50)),
                ('pe_main_firm_strategy', models.CharField(max_length=100)),
                ('aum_cur_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aum_usd_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aum_eur_mn', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
